### ISSUE TITLE
rbokeh documentation page does not load graphics

### ISSUE THREAD

**Issue by gonzmg88** [bokeh/rbokeh#104]
`rbokeh` documentation page javascript (http://hafen.github.io/rbokeh/) does not work.

The page returns the following error
`
http://hafen.github.io/rbokeh/assets/htmlwidgets-0.5/htmlwidgets.js Failed to load resource: the server 
`

The source indeed does not exists in the repo.

**Comment by hafen** [comment]
Thanks!  Don't know how that happened.  It's fixed now.
