### ISSUE TITLE
Remove NAs from line plots

### ISSUE THREAD

**Issue by CesiumLifeJacket** [bokeh/rbokeh#116]
Currently, NA values are just treated as zero in ly_lines.  With a few lines of code in [make_glyph.R] (https://github.com/CesiumLifeJacket/rbokeh/blob/master/R/make_glyph.R)  (lines 114 to 118) I was able remove these NAs for my specific use case, but I'm not sure how robust this is, and in any case the solution's not ideal as it leaves line segments across the removed values.

**Comment by hafen** [comment]
Thanks for the report.  That's definitely not good and I'll fix asap.  This must have snuck in with how NAs are encoded in json and how bokehjs interprets the values.

NAs should never be interpreted as zero.  However, for lines, I like how

**Comment by hafen** [comment]
This is fixed in the dev branch.  Will merge when more testing and documentation is done.
