### ISSUE TITLE
Rotate axis labels in boxplots

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#118]
Is there a way to rotate axis tick labels in figure() or elsewhere?

This comes up with boxplots most often for me.  Levels of a grouping variable may not fit well in the screen written horizontally on the x-axis, but angled or vertically they fit well.

**Comment by hafen** [comment]
Here's an example:

```
figure(ylab = "Height (inches)", width = 600) %>%
  ly_boxplot(voice.part, height, data = lattice::singer) %>%
  x_axis(major_label_orientation = 90)
```

However, this will change when the updates to the dev branch are merged.  I'd actually suggest you use dev.  For that, the command is:

```
figure(ylab = "Height (inches)", width = 600) %>%
  ly_boxplot(voice.part, height, data = lattice::singer) %>%
  theme_axis("x", major_label_orientation = 90)
```

**Comment by jrounds** [comment]
Thanks Ryan.
