### ISSUE TITLE
ly_crect interprets a single character string as a vector of characters (sort of?)

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#119]
Hi, there is a bug when ly_crect is plotting one level of a factor/string.

  Minimal examples this is right:
```
 data = data.frame(x=letters[1:2], y=c("yada1","yada2"))
figure()  %>% ly_crect(x,y, data=data,color="blue")
```
But now wrong:
```
 data = data.frame(x=letters[1:2], y=c("yada1","yada1"))
figure()  %>% ly_crect(x,y, data=data,color="blue")
```

This is in the context of using a ly_heatmap function in a trelliscope display (which often hits corner cases), and in this case the idea was to plot 2 cells for one level of "yada1".   I didn't want "y" to be its own cell, but that is how it comes out.

**Comment by jrounds** [comment]
BTW I tried to walk through the code to understand where this was happening, and I wasn't able to find it.  This may be much lower level than ly_crect, and involve the glyph code.

**Comment by hafen** [comment]
This is strange.  You get the strange behavior even when you do this:

```
figure() %>% ly_crect(letters[1:3], rep("yadayada", 3))
```

But not when you do:

```
figure() %>% ly_crect(letters[1:3], paste("yadayada", 1:3))
```

The output that gets sent to Bokeh looks fine so it may be something I need to dig deeper on the Bokeh side to understand.

**Comment by jrounds** [comment]
It is related to whether or not unique(y) is one thing or more things.  There is a call to unique in the code that creates a range object in the glyph code and if unique only finds 1 string or level that is when things get wonky.

**Comment by hafen** [comment]
Okay - figured it out.  JSON encoding issue.  See here: https://github.com/bokeh/rbokeh/pull/123/files
I'll merge it into the dev branch as soon as tests pass.

**Comment by jrounds** [comment]
Thanks Ryan.

**Comment by jrounds** [comment]
Is this fixed then if I go to dev branch?

**Comment by hafen** [comment]
It's fixed in master now.
