### ISSUE TITLE
Is there a way to created stacked histograms?

### ISSUE THREAD

**Issue by kaneplusplus** [bokeh/rbokeh#120]
In ggplot2 I can create a stacked histogram like this:
```
library(ggplot2)
iris$Quantized.Sepal.Width = factor(round(iris$Sepal.Width))
qplot(x=Quantized.Sepal.Width, y=Sepal.Length, data=iris, fill=Species, geom="bar", 
      position="stack", stat="identity")
```
Is there a way to do this in rbokeh?

**Comment by hafen** [comment]
I just added some preliminary support for this.  It's in the dev branch.  If you don't mind using the dev branch and testing it out, that would be awesome.  See `ly_bar` for examples.

**Comment by kaneplusplus** [comment]
Great thanks!
