### ISSUE TITLE
ly_crect (or subsequent calls) ignores factor order

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#124]
Hi Ryan,

Todays issue related to building ly_heatmap using ly_crect is that ly_crect creates alphabetical order axis labels regardless of if the user has re-ordered the factor that generated the label.

For example,
```
grid = expand.grid(x = factor(letters[4:1]), y = letters[1:4])
grid$value = runif(nrow(grid))  #only purpose is to let boxplots contrast ly_crect
levels(grid$x) = letters[4:1]
levels(grid$x)
boxplot(value ~ x, data=grid)  # comes out d through a
figure() %>% ly_crect(x=x,y=y, data=grid)  #comes out a through d
```

In theory the ideal plotting tool would know that x was a factor and respect the order of x in the factor R type.  Not sure what level this is at for a fix.

**Comment by hafen** [comment]
You actually have complete control over categorical axis limits with any of the layer functions.  Simply supply `xlim = c(...)` inside your call to `figure()` with the order that you desire.  So if it's a factor you can do `xlim = levels(grid$x)`.  I suppose alphabetical is not a good default ordering.  The difficulty is figuring out what the right order is if the person is adding multiple layers with different levels on each layer.

**Comment by jrounds** [comment]
Oh oops.  Okay I just didn't understand.  Thanks!

**Comment by jrounds** [comment]
I never even realized what that "xlim not specified explicitly... calculating..." meant until now.

**Comment by hafen** [comment]
Yes there's actually a ton to document (functions are well documented but need more on the tutorial side).  When axis limits are not explicitly set, it goes through all the data in all the layers and finds the right axis limits.
