### ISSUE TITLE
Anyway to turn a vector of column names into a hover?

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#126]
Can't figure out the easy way to do this:
```
data(iris)
figure() %>% ly_points(Sepal.Length, Sepal.Width, data=iris,hover=as.list(names(iris)))
```

What I want is the hover to be from a vector of column names without having to write them out.  Easy way?

**Comment by hafen** [comment]
You can give hover an actual data frame if that is easier.  So in this case you could do `hover = iris`

**Comment by jrounds** [comment]
Just figured that out. Thanks for prompt reply.  Closing!

**Comment by jrounds** [comment]
it seems to me rbokeh:::get_hover is altered just prior to the follow code to check for class(hn) == "character" it could easily just skip to:
subset(data, select=hn)

``` hn <- deparse(hn)[1]
            hn <- gsub("c\\(|list\\(|\\)| +", "", hn)
            hn <- strsplit(hn, ",")[[1]]
            if (all(!hn %in% names(data))) {
                message("There were no columns: ", paste(hn, 
                  collapse = ", "), " in the data for the hover tool - hover not added")
                return(NULL)
            }
```

Would you accept that if someone made a push request?
