### ISSUE TITLE
ly_points error when glyph variable has one level.

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#127]
Corner case again.

```
data(iris)
data = iris %>% subset(Species == "virginica") 
figure() %>% ly_points(Sepal.Width, Sepal.Length, data=data, glyph=Species)
```

Ideal behavior is probably draw the glyph with one symbol?  But it  fails (without an error) and spams warnings.

**Comment by jrounds** [comment]
BTW that doesn't sound like it can be very annoying, but I made a Trelliscope display with this line of code (not runnable
```		
fig = fig %>% ly_kaplanMeierLines(fit0,col="blue") %>% ly_kaplanMeierPoints(fit0,cur_group0, time="survival_time", hover=cur_group0, col="blue", glyph=vital_status) %>%
					ly_kaplanMeierLines(fit2,col="red") %>% ly_kaplanMeierPoints(fit2,cur_group2, time_var="survival_time", hover=cur_group2, col="red", glyph=vital_status)
```

Where "red" and "blue" are two subsets of the data, and vital status sometimes is all alive or all dead but most often alive and dead, and now essentially each one of those "red" and "blue" need a 
```
if(length(unique(cur_group$vital_status)) == 1)
  figure call without glyph else figure call with glyph
```

**Comment by hafen** [comment]
Thanks for the report.  This been fixed in a soon-to-be-merged-to-master commit.
