### ISSUE TITLE
ly_points color argument used with legends argument errors

### ISSUE THREAD

**Issue by jrounds** [bokeh/rbokeh#132]
Hi,  I was investigating my request for help on bokeh group:

I decided maybe this is an "issue".  There are two arguments that work separately in rbokeh ly_points but they don't work as expected when used together.

Start with 
```
data(iris)
colors = c("red","blue","black")
glyphs = c(13,14,15)
data0 = split(iris,  list(Species=iris$Species))
legends = unlist(lapply(data0, function(s) unique(s$Species)))
i = 1
```
Now these two calls work as expected:
```
#these work
figure() %>% ly_points(Sepal.Length, Sepal.Width, data=data0[[i]], legend = legends[i])
figure() %>% ly_points(Sepal.Length, Sepal.Width, data= data0[[i]], color="red")	
```
But the two arguments together do not work (or certainly do not act as you would expect based on the above result).
```
#does not work
figure() %>% ly_points(Sepal.Length, Sepal.Width, data= data0[[i]], color="red", legend=legends[i])
```

**Comment by hafen** [comment]
Thanks for the report.  We are working on this and several related issues with handling arguments robustly.

**Comment by jrounds** [comment]
I have a trelliscope display waiting on the ability to do this, so I thought I would try to figure out if it could be done at all, and I thought "make a single data.frame".

  I need to plot 4 sets of points.  ("Censored", "Deceased") crossed with ("Type A", "TypeB") .  The censored need to be triangles, deceased need to be circles, Type A needs to be red, Type B needs to be blue.  A legend is required.

So I need to plot basically this:
```
data = expand.grid(rep=1:10, type=c("A","B"), status=c("Censored", "Deceased"))
data$x = runif(nrow(data))
data$y = runif(nrow(data))
figure() %>% ly_points(x,y, data=data, color=type, glyph=status)
```

Is this possible?

**Comment by sedot42** [comment]
Hi, I want to use the `legend` and `color` parameters together with the `hover` parameter. This is not possible without the `data` parameter I think, that's why the workaround does not work for me. Please reopen the issue.
