### ISSUE TITLE
RBokeh hover doesn't work if the x-axis is a string instead of a number

### ISSUE THREAD

**Issue by gryslik** [bokeh/rbokeh#136]
Here's a fully worked out example:

```library(dplyr)
library(rbokeh)

myDF <- as.data.frame(matrix(nrow = 10, ncol = 2))
colnames(myDF) <- c("time", "value")

myDF$time <- rep(LETTERS[1:10])
myDF$value <- rnorm(10)

figure() %>%
  ly_points(.,time, value, data = myDF, hover =list(time, value))```

**Comment by hafen** [comment]
Thanks for the report.  This works with the dev version.  `devtools::install_github("bokeh/rbokeh@dev")`.  Dev is about to be merged to master but I need to update some docs and do some more testing, but use dev for now.

**Comment by hafen** [comment]
This was fixed a while back but forgot to close it.  Please reopen if you experience any related issues.
