### ISSUE TITLE
Scatter plot preview example relies on data frame column order

### ISSUE THREAD

**Issue by saun4app** [bokeh/rbokeh#140]
Scatter plot preview example (ly_points, ly_abline), appears to relies on the column order of data frame, instead of formula. For example, the original example (see get_rbokeh() below) looks good.  However, if change the column order of cars data frame to ('dist','speed'), instead of ('speed', 'dist') the result looks off (see get_rbokeh_reverse_column() below); the x and y values on the chart follows the order of data frame (not the formula), the lm line looks off. 

```{r}
get_rbokeh <- function() {
  z <- lm(dist ~ speed, data = cars) # cars column order is ('speed', 'dist')
  p <- figure(width = 600, height = 600) %>%
    ly_points(cars, hover = cars) %>%
    ly_lines(lowess(cars), legend = "lowess") %>%
    ly_abline(z, type = 2, legend = "lm")
  
  return(p)
}
get_rbokeh()
```

```{r}
get_rbokeh_reverse_column <- function() {
	cars_df <- cars[c('dist','speed')] # change the order of columns

  z <- lm(dist ~ speed, data = cars_df) # same column order as get_rbokeh()
  p <- figure(width = 600, height = 600) %>%
    ly_points(cars_df, hover = cars_df) %>%
    ly_lines(lowess(cars_df), legend = "lowess") %>%
    ly_abline(z, type = 2, legend = "lm")
  
  return(p)
}
get_rbokeh_reverse_column()
```

**Comment by hafen** [comment]
Thanks for the report.  This is actually how it supposed to work.  If you give a data frame as an argument to `ly_points()` it will grab the first column for the x-axis and the second column for the y-axis.  

Note that your formula in `lm()` has nothing to do with `ly_points()`, just `ly_abline()`.

If you want to explicitly specify the x and y variables for `ly_points()`, you can do the following:

```r
z <- lm(dist ~ speed, data = cars) # cars column order is ('speed', 'dist')
figure(width = 600, height = 600) %>%
  ly_points(speed, dist, data = cars, hover = cars) %>%
  ly_lines(lowess(cars), legend = "lowess") %>%
  ly_abline(z, type = 2, legend = "lm")
```
