### ISSUE TITLE
Points or polygon offset over map

### ISSUE THREAD

**Issue by masip85** [bokeh/rbokeh#142]
![captura de pantalla 2015-11-28 a las 2 52 36](https://cloud.githubusercontent.com/assets/12863854/11449563/1aaefc24-957b-11e5-90c4-d44cfb716af0.png)

If I get red square corners coordinates , and set them to google maps web directly, the coordinates fit exactly with build corners. Something happens when I do something like:

gmap ... %>%
ly_polygons %>%
ly_points %>%

Offset appears at all Chicago city in this case.

**Comment by hafen** [comment]
Thanks - this is an issue with Bokeh and I have an issue opened here: https://github.com/bokeh/bokeh/issues/2964

**Comment by hafen** [comment]
Recent updates to BokehJS seems to have cleared up this issue.  Adding layers on top of maps have been consistently aligned for me lately.  Can you re-try your above example with the latest rbokeh?

**Comment by hafen** [comment]
Closing - let me know if it is still an issue for you.
