### ISSUE TITLE
ly_text renders "[object Object]" if text attribute passed a string

### ISSUE THREAD

**Issue by alistaire47** [bokeh/rbokeh#143]
When the `text` attribute of `ly_text` is passed a string, it renders "[object Object]" instead of the supplied string. For example:

```r
figure() %>% ly_text(1, 1, text = 'Hello world')
```
renders
![Image of plot with object Object](http://i65.tinypic.com/282ou4w.jpg)

I found similar closed issues [30](https://github.com/bokeh/rbokeh/issues/30) and [38](https://github.com/bokeh/rbokeh/issues/38), but the issue remains on RBokeh v. 0.2.3.2. The other issues led me to wrap the string in a list,
```r
figure() %>% ly_text(1, 1, text = list('Hello world'))
```
 which renders
![Image of plot with Hello world](http://i63.tinypic.com/2hpnhtt.jpg)
like it should. If the parameter can't be edited to handle a string (in the short term, at least), could the documentation get updated to specify that `text` takes a list? It's really counterintuitive, so I suspect more people will run into the issue.

**Comment by hafen** [comment]
Thanks for the report and your patience.  Looking into it.  We've been doing a lot under the hood and this issue should be addressed pretty soon.

**Comment by hafen** [comment]
This is fixed in most recent version.
