### ISSUE TITLE
Update to Bokeh 0.8 rc and make sure things work

### ISSUE THREAD

**Issue by hafen** [bokeh/rbokeh#15]

**Comment by timelyportfolio** [comment]
I have built and tested locally. Want me to submit pull to save you the build step?

**Comment by hafen** [comment]
Cool!  Did everything in rbokeh still work?  It looks like some axis things have changed, etc.  Can we put this in a separate branch just to make sure everything works before it's in master?

**Comment by timelyportfolio** [comment]
Sure, I have put here for now https://github.com/timelyportfolio/rbokeh/tree/fix/update-bokehjs.  I'll run through the tests/examples again to make sure everything working as expected.

**Comment by hafen** [comment]
Great.  I think I'll create an "initial_release" branch here that we can merge this in with and all other work on issues I've flagged on the "initial release".  Does that sound good?  I'm a bit new to well-organized collaboration on github.

**Comment by timelyportfolio** [comment]
Sounds reasonable and understandable to me.  I have run all the examples I could find and have not seen any problems with the newest bokeh.js

**Comment by bryevdv** [comment]
FYI 0.8 final is up on CDN now: http://cdn.pydata.org/bokeh/release/bokeh-0.8.0.min.js

**Comment by timelyportfolio** [comment]
I think our version is current, but to make sure, @hafen, want me to do another pull with this exact build from the cdn?

**Comment by hafen** [comment]
Thanks @timelyportfolio.  I just pulled the final from the CDN and pushed to my repo.  Also fixed #6 and #7.  I will merge when tests pass.

**Comment by timelyportfolio** [comment]
awesome.  will watch and check/test on mine as soon as I see it merged.
