### ISSUE TITLE
Rbokeh -- Trouble with ly_abline()

### ISSUE THREAD

**Issue by stevemiller79** [bokeh/rbokeh#156]
I have a index portfolio performance chart where the x-axis is date and y-axis is growth of $1, computed from daily percent change numbers. I wish to draw a horizontal line at $1 to indicate break-even, but ly_abline() is barfing at the x-axis date. If I change date to integer, ly_abline with slope (b) and intercept (a) works, though I cannot get ly_abline with v or h to work regardless. This doesn't present a problem with R core, lattice, or ggplot2 graphics.

Steve M

**Comment by hafen** [comment]
Interesting.  Can you provide an example?

**Comment by hafen** [comment]
I don't have an example to work with, but I have done some work to make `ly_abline` more robust to axes.  Could you give this a try and see if it fixes your issue?

```r
devtools::install_github("bokeh/rbokeh@dev")
```

**Comment by dppalomar** [comment]
Dear Ryan,

First of all, thanks for this great package.
I found this thread because I had the same problem, I can tell you how to reproduce the error. Basically ly_abline does not work with dates, that's it.

This code does not use ly_abline and works well:
x <- seq(from=as.Date("2010-01-01"), to=as.Date("2010-02-01"), "days")
y <- seq(from=1, by=1, length.out=length(x))
rbokeh::figure() %>% 
  ly_lines(x, y, width=2) %>%
  ly_lines(c(as.Date("2010-01-01"), as.Date("2010-02-01")), c(15, 15))

This should do the same with ly_abline but fails:
rbokeh::figure() %>% 
  ly_lines(x, y, width=2) %>%
  ly_abline(h=15)

This uses ly_line but not using dates, instead I just use some numbers and it works:
rbokeh::figure() %>% 
  ly_lines(1:length(x), y, width=2) %>%
  ly_abline(h=15)


And now that I am writing, I have another request. The function rbokeh2html does not work well with xts. Basically, it only works if I use y=as.numeric(...). If I don't use as.numeric(), then it gives an error about asJSON. Perhaps this could be of use: https://gist.github.com/vst/1388190

Thanks again for everything!
Daniel

**Comment by hafen** [comment]
Thanks @dppalomar.  Did you run your above examples with the latest version of rbokeh, installable with `devtools::install_github("bokeh/rbokeh@dev")` ?  I fixed some date issues in this version and the examples appear to work for me.

Concerning xts output, is it just `rbokeh2html` that doesn't work?  Do those plots render correctly if you simply print them?  It would definitely be good to support this, so if you can provide me an example I can reproduce, I'll look into it.

**Comment by dppalomar** [comment]
Ryan, you are right that installing the latest version fixes the issue with ly_abline and dates. Thanks.

However, that version gave me some new issues with grid_plot (which does not respect now the width and height of the individual figures). It also gave me a new issue with rbokeh2html (the generated html does not open properly in my browser, it is now blank). So I am going back to the more stable version in CRAN.

But before I finish, let me tell you about a couple of issues I also have with the CRAN version of rbokeh:
1) If I redefine the format for the x axis with 
x_axis(label = "Date", format = list(years="%Y", months="%b%y", days="%Y/%m/%d"))
I get the proper new format for years in the plots in the Viewer (they look like 2012, 2013, etc.) but if I use rbokeh2html this formatting disappears and it goes to the default one (which looks like '12, '13, etc.)
2) Another issue with rbokeh2html when using xts. The following code works fine when I plot it in the Viewer with "p" as well as in the html when I use rbokeh2html:

library(xts)
data(sample_matrix)
matrix_xts <- as.xts(sample_matrix,dateFormat='Date')
p <- rbokeh::figure() %>%
  ly_lines(x=1:180, y=as.numeric(matrix_xts[,"Open"]))
p
rbokeh2html.open(p, file="test.html")

However, if I don't use the "as.numeric"then the rbokeh2html does not work and gives me the error "Error: No method asJSON S3 class: zoo":
p <- rbokeh::figure() %>%
  ly_lines(x=1:180, y=matrix_xts[,"Open"])
p
rbokeh2html.open(p, file="test.html")


Thanks!
Daniel

**Comment by hafen** [comment]
Thanks Daniel.  I'll take a look at these examples.

Also, I am planning to release the dev version of rbokeh to CRAN very soon.  I've been using it a lot and consider it to be quite stable, but it's difficult to test every corner in a systematic way and it appears you have a few issues with it.  If you don't mind, could you provide me with reproducible examples of grid plot and rbokeh2html that don't work the way you expect in the dev version?  All of the examples I have of these are working the way I expect, so I want to make sure I am covering every case before I release.

**Comment by dppalomar** [comment]
Ryan, below I pass you the code with three issues that I have encountered. You can reproduce the errors now.

Issues:

1) Using the rbokeh version in GitHub, rbokeh2html does not generate a correct html file that can be opened. I open with Chrome and nothing appears. The same with Safari.

x <- seq(from=as.Date("2010-01-01"), to=as.Date("2015-02-01"), "days")
y <- seq(from=1, by=1, length.out=length(x))
p <- figure() %>% 
  ly_lines(x, y, width=2) %>%
  x_axis(format = list(years="%Y", months="%b%y", days="%Y/%m/%d"))
rbokeh2html(p, file="test.html")


2) Size of subplots lost in grid_plot (still using GitHut version). This is the code:

x <- seq(from=as.Date("2010-01-01"), to=as.Date("2015-02-01"), "days")
y <- seq(from=1, by=1, length.out=length(x))
p1 <- figure(width=600, height=100) %>% 
  ly_lines(x, y, width=2) %>%
  x_axis(format = list(years="%Y", months="%b%y", days="%Y/%m/%d"))
p2 <- figure(width=600, height=100) %>% 
  ly_lines(x, y, width=2) %>%
  x_axis(format = list(years="%Y", months="%b%y", days="%Y/%m/%d"))
p <- grid_plot(list(p1, p2), ncol=1)

p1 will give you the correct sized plot as well as p2. But p will lose the size and give you both plots with default square size.


3) Now, going back to the CRAN version. The formatting of the dates is lost in rbokeh2html. If I use the example in 1), in the Viewer I can see the years 2010  2011 … But in the html version, they revert to the default ’10  ’11  ’12  ’13 …

Thanks
Daniel
