### ISSUE TITLE
Support full control over axes

### ISSUE THREAD

**Issue by hafen** [bokeh/rbokeh#16]
This will be helpful for GridPlot, but very useful in general for finer control over axes.  Should be as simple as making the following parameters options in `x_axis()` and `y_axis()` and adding them to our model representation:

http://bokeh.pydata.org/en/latest/docs/reference/models.html#axis

**Comment by timelyportfolio** [comment]
I think I'll need this for the in development `ly_bar` #8

**Comment by timelyportfolio** [comment]
These changes look great.  Do you have any additional examples/tests?  I can try to make some once I get a handle on all of them.

**Comment by hafen** [comment]
I should have added some tests with some of the different settings.  You can see what is possible by looking at the "Additional parameters" section in `x_axis`: http://hafen.github.io/rbokeh/rd.html#x_axis.  To get at these, you need to explicitly add `x_axis()` to your figure.  The thinking is that you get the most basic defaults for axis control in the call to `figure()` and if you want any customization, you add calls to `x_axis()` or `y_axis()`.
