### ISSUE TITLE
BokehJS v0.12

### ISSUE THREAD

**Issue by brett-patterson** [bokeh/rbokeh#160]
Are there any plans to support BokehJS v0.12? It doesn't seem to work out of the box, so I assumed there were some changes to the JSON spec, but I didn't investigate very thoroughly. I'd be happy to help if this is something you'd like to do.

**Comment by pdelboca** [comment]
It would be great to update due that Google Maps is no longer working due to API Update. It was 
[fixed in V0.12](https://github.com/bokeh/bokeh/issues/4658)

**Comment by hafen** [comment]
Sorry for the delay.  My github notifications are going to the wrong mailbox.  I started work on a v0.12 branch and got caught up in some other deadlines but will turn focus to this.  Addressing the google maps issue is also on the table.

**Comment by hafen** [comment]
@brett-patterson thanks for offering to help.  I have gone through and found what I think to be all the critical changes in the JSON models and I have a *very experimental* branch working with 0.12 with the `api_key` added for google maps.  I'll be doing more work and testing on it, but if you want to try it out, `devtools::install_github("hafen/rbokeh@bokeh0.12")`.

**Comment by hafen** [comment]
I've done quite a bit of work and everything seems to be working with 0.12.  Grid plots took a lot of work and there were quite a few other little things.  I wouldn't mind some help testing it out.  If you want to install:

```r
devtools::install_github("bokeh/rbokeh@dev")
```

Let me know if you see any issues.

**Comment by brett-patterson** [comment]
Thanks so much for doing this work @hafen. I'll check it out soon and let you know how it goes.
