### ISSUE TITLE
ly_bar bombs on input with only one row

### ISSUE THREAD

**Issue by igoldin2u** [bokeh/rbokeh#165]
a <- data.frame(x="a", n=1)
    ly_bar(figure(), x="x", y="n", data=a)
    # Error in FUN(X[[i]], ...) : invalid 'type' (character) of argument

This doesn't bomb, but the plot is silly:

    ly_bar(figure(), x="x", data=a)

**Comment by hafen** [comment]
If you are providing a data argument you don't quote the inputs:

```r
a <- data.frame(x = "a", n = 1)
ly_bar(figure(), x = x, y = n, data = a)
```

**Comment by igoldin2u** [comment]
Oy. In my case, the name of the input column is passed in as a character string. If `ly_bar` insists on NSE, then is there a standard evaluation version, like how `dplyr` has `filter` and `filter_`?

Incidentally, `ly_bar` works great if I do quote the input column names and the input data has 2 or more rows. Is that just a lucky accident?

**Comment by hafen** [comment]
I see.  If you are using variables to get at column names, you can also do something like this:

```r
a <- data.frame(x = "a", n = 1)
xvar <- "x"
yvar <- "y"

ly_bar(figure(), x = a[[xvar]], y = a[[yvar]], xlab = xvar, ylab = yvar)
```

I'll look into why it does / doesn't work with >1 row / 1 row.  There's a lot of logic going on behind the scenes wrt NSE that can get tricky.
