### ISSUE TITLE
Proposal: Customizing outlier points in boxplots

### ISSUE THREAD

**Issue by lianos** [bokeh/rbokeh#177]
Sorry to keep coming back to this.

How about adding `outlier_size` and `outlier_glyph` parameters to `ly_boxplot` so that the user can customize these?

Although `with_outliers` was recently added to the codebase, I propose we mimic the ggplot2 behavior that if any of the above new params is set to `NA`, then outliers are hidden altogether ... and perhaps we remove the `with_outliers` parameter, to boot.

Can provide a PR ASAP if given the thumbs up.

**Comment by hafen** [comment]
That sounds great to me.  `with_outliers` hasn't been released to CRAN yet so not a big deal to change / remove it in favor of this.  PR would be greatly appreciated.

**Comment by lianos** [comment]
OK, will do.

Should I branch off of `dev` w/o PR #176 merged?

Or do you want to merge that first?

Or I can just add it to PR #176, and then can merge the whole shebang.

**Comment by hafen** [comment]
Sure add to #176 - was just taking a look at it and it looks good.  Might as well add and merge once.

**Comment by lianos** [comment]
This is implemented in commit 66fbbb53ae1d5f43172c2a2544c5d214e3449e0e.
