### ISSUE TITLE
grid_plot does not respect x_axis and y_axis modifications

### ISSUE THREAD

**Issue by igoldin2u** [bokeh/rbokeh#178]
`grid_plot(same_axes=TRUE)` does not generate the same axes for all subplots once there are changes to `x_axis` and `y_axis`. In this example, `grid_plot` ignores `grid=FALSE` and `desired_num_ticks=16`

```
iris %>% 
  group_by(Species) %>%
  dplyr::do(dummy = 
    ly_points(figure(), Sepal.Length, Sepal.Width, data=.) %>% 
      x_axis(grid=FALSE) %>%
      y_axis(desired_num_ticks=16)) %>%
  { as.list(.[['dummy']]) } %>%
  grid_plot(nrow = 2, ncol = 2, same_axes = TRUE )

```

**Comment by hafen** [comment]
Thanks!  Looking into it.

**Comment by hafen** [comment]
This is fixed in the dev branch.  Hope to merge to master by end of week.

**Comment by igoldin2u** [comment]
Confirming fixed. Incidentally, the axis label is repeated for each subplot. I agree that the tick labels should be repeated, but I think it's sufficient to show the axis label just once.

**Comment by hafen** [comment]
Great thanks for checking.  Concerning the axis labels repeating, I agree that they should be shown only once but I'm not sure how to make that happen with Bokeh.  If you see an example of a grid plot in Bokeh that has this behavior, please let me know - I generally figure out how features work in Bokeh by reverse engineering the json spec.
