### ISSUE TITLE
glyph "magically" set to "Image" when both glyph and color are set (in dev)

### ISSUE THREAD

**Issue by lianos** [bokeh/rbokeh#179]
I've been trying to dig myself out from under this one for a while but I'm hoping @hafen can spot this out immediately.

I'm working with the dev version, and specifying both color and glyph is throwing an error. I know it's a WIP but I figured feedback early in the process could be helpful

```r
library(rbokeh)
ir <- transform(iris, group = sample(c("a", "b"), nrow(iris), replace=TRUE))

## works
figure(ir) %>% ly_points(Sepal.Length, Sepal.Width, color=Species)

## works
figure(ir) %>% ly_points(Sepal.Length, Sepal.Width, glyph=group)

## breaks
figure(ir) %>% ly_points(Sepal.Length, Sepal.Width, glyph=group, color=Species)
## Error in if (glyph == "Image") { : argument is of length zero
```

**Comment by hafen** [comment]
Thanks for this case.  I'll look into it right away.

**Comment by hafen** [comment]
I've fixed it in the dev branch.  Feel free to give it a try and make sure it works the way you expect.

**Comment by lianos** [comment]
Nailed it, thanks!
