### ISSUE TITLE
Can't change plot background color

### ISSUE THREAD

**Issue by DeliciousPickle** [bokeh/rbokeh#182]
I've tried every way I can find to change the background color of an ly_bar plot, but no matter what I try it stubbornly remains white.  theme_plot(background_fill) doesn't seem to work at all.  Can you please tell me how to change the background color of an ly_bar plot?  Any examples would be greatly appreciated.

**Comment by DeliciousPickle** [comment]
I should add that I'm experiencing this problem in the context of a Shiny application.  Attached are ui.R and server.R files for a simple example, based on one of the rbokeh examples at http://hafen.github.io/rbokeh/.   (.txt extension added so the files would upload here.)

[server.R.txt](https://github.com/bokeh/rbokeh/files/464949/server.R.txt)
[ui.R.txt](https://github.com/bokeh/rbokeh/files/464950/ui.R.txt)

**Comment by DeliciousPickle** [comment]
Here's another example, this time NOT in Shiny.  Still doesn't color the background.

`require(rbokeh)

p <- figure() %>%
    ly_points(
        Sepal.Length, Sepal.Width, data = iris,
        color = Species, glyph = Species,
        hover = list(Sepal.Length, Sepal.Width)
    ) %>%

    theme_plot(
        background_fill = 'red'
    )

p
`

**Comment by hafen** [comment]
This is working for me with the latest rbokeh (which will hopefully be on CRAN this upcoming week).

You can install with:

install_github("bokeh/rbokeh@dev")

Then you need to use background_fill_color instead of background_fill and your example will work.  Note there is also now a background_fill_alpha parameter as well.

Ryan

**Comment by DeliciousPickle** [comment]
Thanks!  I'll give it a try.
