### ISSUE TITLE
In grid_plot, can't format title

### ISSUE THREAD

**Issue by igoldin2u** [bokeh/rbokeh#185]
In a grid plot, specifying any parameters to `theme_plot` that affect plot title makes the whole grid plot blank.

```
library(dplyr)
data_frame_to_lofl <- function(figs, xcol, ycol, figcol) {
  lapply(split(figs, figs[, xcol]), function(d1) {
    lapply(split(d1, d1[, ycol]), function(d2) {
      d2[, figcol][[1]][[1]]
    })
  })
}

ggplot2::diamonds %>%
  sample_frac(0.1) %>% # Too many rows in diamonds for this example
  group_by(cut, color) %>%
  do(fig=ly_points(figure(), x=carat, y=price, data=.) %>%
       theme_plot(title_text_color="#0066FF")) %>%
  data_frame_to_lofl("cut", "color", "fig") %>% # Create a list of lists
  grid_plot(same_axes=TRUE)

```

**Comment by hafen** [comment]
Thanks.  This is on my list to check out (as well as the other examples you have provided... - thanks for your patience - I've been traveling the past 2 weeks).  I hope to knock these out early next week.

**Comment by igoldin2u** [comment]
I think the bigger point with `grid_plot` issues is that there needs to be a canvas for all the subplots, and that one needs to manipulate properties of that canvas: set the main title, show one axis label (rather than one per subplot), show one legend (rather than one per subplot), etc. I didn't file a separate issue (I could!), but right now, you might even have a factor level that is colored differently in different subplots.

**Comment by hafen** [comment]
I fixed this in the latest commit: https://github.com/hafen/rbokeh/tree/master.  The way it works is you can theme your grid plots after the GridPlot object has been created.  You can still do it before as well, but things like titles are overwritten if you give it a named list.

Here are some examples:

```r
idx <- split(1:150, iris$Species)
figs <- lapply(idx, function(x) {
  figure(width = 300, height = 300) %>%
    ly_points(Sepal.Length, Sepal.Width, data = iris[x, ],
      hover = list(Sepal.Length, Sepal.Width))
})

grid_plot(figs) %>%
  theme_title(text_color = "red") %>%
  theme_plot(background_fill_color = "#E6E6E6",
    outline_line_color = "white") %>%
  theme_grid(c("x", "y"), grid_line_color = "white",
    minor_grid_line_color = "white",
    minor_grid_line_alpha = 0.4) %>%
  theme_axis(c("x", "y"), axis_line_color = "white",
    major_label_text_color = "#7F7F7F",
    major_tick_line_color = "#7F7F7F",
    minor_tick_line_alpha = 0, num_minor_ticks = 2)

grid_plot(figs) %>%
  set_theme(bk_ggplot_theme)
```
