### ISSUE TITLE
Generating histogram

### ISSUE THREAD

**Issue by carbonmetrics** [bokeh/rbokeh#188]
I am trying to generate histograms via `ly_hist` and `ly_bar` and got unexpected results. 

A question on [stackoverflow](https://stackoverflow.com/questions/40154386/how-can-i-make-a-histogram-in-rbokeh) did not give useful answers. 

I am therefore submitting the question as an issue.

**Comment by igoldin2u** [comment]
Try this: use `hist(..., plot=FALSE)` to compute the histogram without visualizing it, with just the breaks or bin width that you want. Then see if `ly_hist()` actually shows the wrong output with the same breaks. If it does, you've found a bug, but only then.

**Comment by hafen** [comment]
I answered the question on SO.  But it brought up a couple issues to be addressed that would make things more convenient.  I've opened #189 and #190 and am closing this.
