### ISSUE TITLE
get gylph error with ly_crect

### ISSUE THREAD

**Issue by timelyportfolio** [bokeh/rbokeh#2]
cross-posted on mailing-list since not sure where to post.

I thought a correlation plot based on the periodic table would be a good example, but I run into **this error**.

```
Error in if (!glyph_name %in% names(glyph_props)) glyph_name <- "mappedGlyph" : 
  argument is of length zero
```

and separately get **no hover on the points** (but the periodic table works).

The code to reproduce is here.  The `ly_points` works fine, but not `ly_crect`.

```R
# correlation plot with ly_text using cor example
(Cl <- cor(longley))
# convert to long format with tidyr::gather
Cl_long <- tidyr::gather( data.frame(x = rownames(Cl),Cl), y, correlation, -x  )
# build our plot
(p <- figure(
  title = "Correlation Plot"
  ,ylim = unique(Cl_long$indicator)
  ,xlim = unique(Cl_long$indicator)
  ,xgrid = FALSE
  ,ygrid = FALSE
  ,height = 700
  ,width = 700
  ,tools = c("hover")
) %>%
  # get a plot but hover not working for me
  ly_points( x, y, data = Cl_long, color = correlation, size = correlation, hover = c(x,y) )
)
# but this doesn't work
p %>% ly_crect( x, y, data = Cl_long, color = correlation )
```

and I might just be using `ly_crect` incorrectly, since I did see that this sort of works.

```R
(p <- figure(
  title = "Correlation Plot"
  ,ylim = unique(Cl_long$indicator)
  ,xlim = unique(Cl_long$indicator)
  ,xgrid = FALSE
  ,ygrid = FALSE
  ,height = 700
  ,width = 700
  ,tools = c("hover")
) %>%
  ly_points( x, y, data = Cl_long, glyph=15, size = correlation, color = correlation )
)
```

**Comment by hafen** [comment]
Thanks for the report.  I have addressed the `crect` issue and hover works with that.

However, I can't get hover to work on points.  If you first convert x and y to integer, then hover works fine.  I don't know if this is an issue with categorical axes.  I think there are some issues with categorical axes I am not aware of, for example, a possibly related issue is that none of the zoom tools work on categorical axes.  Perhaps @bryevdv has some input here.

**Comment by bryevdv** [comment]
There should not be any issues with hover and categorical axes. Regarding pan/zoom I just pushed a PR to fix that.

**Comment by timelyportfolio** [comment]
I found this old issue https://github.com/bokeh/bokeh/issues/463, but looks like it had been resolved.

I can confirm `crect` working now on my end for both render and hover.

```
 p %>% ly_crect( x, y, data = Cl_long, color = correlation, hover = list(x,y,correlation) )
```

**Comment by hafen** [comment]
Glad the crect is working working.  

@bryevdv, yes I am puzzled - nothing changes in the way the model is put together for rect vs points (points is basically a wrapper around all the different markers).  I could send the model JSON if that is useful for quickly picking out where I might be doing something wrong.

Along those lines, when you start playing around in R, I hope to push some docs up soon about this, but a nice function to know is `print_model_json(p)` which will give the JSON sent to bokehjs.  With `pbcopy=TRUE` it will send it to the clipboard on mac.

**Comment by hafen** [comment]
@timelyportfolio, this example brings up the importance of improving the theme system so you have a bit more control over the mappings of variables to colors / sizes.  Of course you can manually compute the colors and sizes you want and send them, but it'd be nice to control through the theme.  I'll post an issue about this soon.

**Comment by bryevdv** [comment]
Theming is an area where improvements directly to BokehJS would benefit everyone. :)

**Comment by timelyportfolio** [comment]
Ok, with `bokeh-v0.9` I think I can close this.  Thanks @bryevdv and @hafen
