### ISSUE TITLE
NA values correctly skipped in linear scale but not in log scale

### ISSUE THREAD

**Issue by zebulon2** [bokeh/rbokeh#204]
Hi,

I found what I believe to be an issue with the handling of NA values when doing a figure with a log axis.

Here is a code example:
```
library(reshape2)
library(rbokeh)

# dummy data
data <- matrix(c(51,43,22,92,28,NA,68,22,9),ncol=2,byrow=TRUE)
mData<-melt(data, id='V1', variable.name = "V2")

p <- figure() %>%
  ly_points(Var1, value, data = mData,
            color=Var2,
            legend=FALSE) %>%
  ly_lines(Var1, value, data = mData,
           color=Var2,
           legend=FALSE)
p
```

The NA value is skipped correctly:

![rbokeh_y_linear](https://cloud.githubusercontent.com/assets/1568591/24096181/6c4a666c-0d58-11e7-8739-6299aaf6e53f.png)

Now if I type
`> y_axis(p, log=TRUE)`

The NA value is not skipped and leads to this issue:
![rbokeh_y_log](https://cloud.githubusercontent.com/assets/1568591/24096228/a659738e-0d58-11e7-9961-366bb67aec2d.png)

This of course happens with imported data from CSV where missing values are replaced with "NA". I do not want to remove rows with NAs because that would lead to lose significant values in a table with several series.

Am I doing something wrong or is it genuinely an issue? Thanks.

**Comment by zebulon2** [comment]
I wanted to update this report: this is not a rbokeh issue, but a problem in bokeh itself, which I reported here: https://github.com/bokeh/bokeh/issues/6035.

**Comment by hafen** [comment]
Thanks. And thanks for tackling the issue too!
