### ISSUE TITLE
axis range does not adjust based on data in view

### ISSUE THREAD

**Issue by tr8dr** [bokeh/rbokeh#208]
When **xlim** is set, constraining the view to a smaller set of data, the y range reflects the data range of the whole series _rather than the range of visible data_.  This is true for the initial state of rendering as well as when the data is panned.   

If this is the correct default behavior, is there a way (even if is a javascript-side hack) to get the y-range to adjust to the range of visible data?   

If this cannot be reasonably adjusted through the API or javascript side, is there a server-side callback I can receive to adjust the range on a pan or other manipulation of visible data?

```R
require(rbokeh)

x <- seq(as.Date('2010-1-1'), as.Date('2017-1-1'), by='days')
len <- NROW(x)
y <- (1:len) * 5e-2 + rnorm(len, sd=10)

## render
range <- c(x[1], x[200])

figure(width=800,height=300, xlim=range) %>%
    ly_lines (x, y) %>%
    tool_pan(dimensions='width')
```

Have included screenshot of what expect to see and one of what actually get. 
![expected](https://cloud.githubusercontent.com/assets/3257426/25362043/99f40374-291f-11e7-8271-e2745d6eca13.png)
![actual](https://cloud.githubusercontent.com/assets/3257426/25362044/9bc37b62-291f-11e7-83b4-0839c043c4ea.png)

**Comment by tr8dr** [comment]
I figured this out, by writing custom JS:

```R
cb <- "
    var plot = cb_obj.plots[0];

    var data = points_data.get('data')
    var x = data['x']
    var y = data['y']

    Xo = x[0]
    var Xstart = plot.x_range.start;
    var Xend = plot.x_range.end;

    function sGE (e) { return e >= Xstart; } 
    function eGE (e) { return e >= Xend; } 
    function fixstart (i) { return i >= 0 ? i : x.length - 20; } 
    function fixend (i) { return i > 0 ? i : x.length - 1; } 
    
    var Istart = fixstart(x.findIndex(sGE))
    var Iend = fixend(x.findIndex(eGE))

    var yview = y.slice(Istart, Iend+1);
    var yv = [Math.min(...yview),Math.max(...yview)];
    var dy = yv[1] - yv[0];

    cb_obj.start = yv[0]-0.15*dy;
    cb_obj.end = yv[1]+0.15*dy;
"

x <- seq(as.Date('2010-1-1'), as.Date('2017-1-1'), by='days')
len <- NROW(x)
y <- (1:len) * 5e-2 + rnorm(len, sd=10)

range <- c(x[1], x[200])
figure(width=800,height=300, xlim=range) %>%
    ly_lines (x, y, lname = "points", lgroup='g1') %>%
    y_range(callback = custom_callback(cb, lnames='points'))

```
It would be nice to have an option to do this automatically in a future version of bokeh / rbokeh.

**Comment by hafen** [comment]
Oh great! I'm glad you were able to work this out. I started writing up a solution the other day and had several things come up that kept me from completing it.

It would be nice for the callback to be responsive to changes in either axis. For example, if you zoom in too much on just the x-axis and then zoom back out in just the x-axis (by using the wheel zoom tool while hovering over the x axis area), the y-axis doesn't update. FWIW here's what I was working on. The only problem is that the y-axis object does not respond to being updated.

```r
library(rbokeh)
set.seed(1234)
figure() %>%
  ly_points(rnorm(100), rnorm(100), lname = "pts") %>%
  x_range(callback = custom_callback(
    code = "
var x = pts_data.get_column('x');
var y = pts_data.get_column('y');
var x1 = range.get('start')
var x2 = range.get('end')
var y1 = NaN
var y2 = NaN

for (i = 0; i < x.length; i++) {
  if (x[i] >= x1 && x[i] <= x2) {
    if (isNaN(y1)) {
      y1 = y[i]
    } else {
      y1 = Math.min(y1, y[i])
    }
    if (isNaN(y2)) {
      y2 = y[i]
    } else {
      y2 = Math.max(y2, y[i])
    }
  }
}

// We need to find the y-axis model object since we don't know its id until after the plot is rendered.
// To find it, loop over models until we find one with a "start" attribute that isn't the x-range model.
var mods = range.document._all_models
var keys = Object.keys(mods)
for (i = 0; i < keys.length; i++) {
  if (keys[i] != range.id && mods[keys[i]].start != undefined) {
    mods[keys[i]].set('start', 1)
    mods[keys[i]].set('end', 2)
  }
}
", "pts"))
```

**Comment by hafen** [comment]
Also, as for the default behavior, I'm not sure if the y axis limits should adapt to data according to a custom-set x axis range by default, although I hadn't thought of this scenario. It seems that if a user in the state of mind to specify a custom axis range for one axis, they would also do so for the other if they wanted complete control. For a frame of reference, this is also the default behavior of ggplot2:

```r
library(ggplot2)
qplot(mpg, wt, data = mtcars)
qplot(mpg, wt, data = mtcars) + xlim(20, 25)
```

A general approach to a callback for adjusting the range could be difficult due to the possibility of several layers on a plot to account for, but it would be great to have as an option if it could be worked out generally.

**Comment by tr8dr** [comment]
I had the same problem re: the y axis object not responding to updates.   the kludge was to put the event on the y_range object, so that the cb_obj is the y axis.  This object does respond to changes.   I think the option / behavior should be an option in core BokehJS so that rbokeh can just latch into it.  I will add as a suggestion in the main bokeh project at some point.

**Comment by hafen** [comment]
Great idea. The more that can happen in core BokehJS the better!
