### ISSUE TITLE
theme_title text_align does not work

### ISSUE THREAD

**Issue by claire-roberts** [bokeh/rbokeh#211]
I'm trying to center align my plot title and it seems that theme_title(text_align='center') does not work.  
An example is below

figure(title="Plot") %>%  
  ly_points(1:10) %>%
  theme_plot(background_fill_color = "#E6E6E6",
             outline_line_color = "white") %>%
  theme_grid(c("x", "y"), grid_line_color = "white",
             minor_grid_line_color = "white",
             minor_grid_line_alpha = 0.4) %>%
  theme_axis(c("x", "y"), axis_line_color = "white",
             major_label_text_color = "#7F7F7F",
             major_tick_line_color = "#7F7F7F",
             minor_tick_line_alpha = 0, num_minor_ticks = 2,
             major_label_text_font_style='italic',
             major_label_text_font = 'times') %>% 
  theme_title(text_align='center')

Any help would be appreciated.
Thanks!

**Comment by hafen** [comment]
Oops - It looks like the align parameter name has been changed in Bokeh to just `align` instead of `test_align`. I just fixed this on the master branch. I have some other changes to work in before I put this update on CRAN, but you can install from github for now to get this fix. Thanks.
