### ISSUE TITLE
Warnings related to `I(NULL)` in R 3.4.0

### ISSUE THREAD

**Issue by aforren1** [bokeh/rbokeh#216]
`structure(NULL, ...)` , and therefore `I(NULL)`, started giving warnings in R 3.4.0 (news [here](http://developer.r-project.org/blosxom.cgi/R-devel/2016/12/28#n2016-12-28)).

Reproducible example:
```r
# devtools::install_github('bokeh/rbokeh')
library(rbokeh)
figure()
```
Running on R 3.4.0 (Windows 10) leads to warnings of:
```r
1: In structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```
One warning stemmed from htmlwidgets, but was fixed in https://github.com/ramnathv/htmlwidgets/pull/270.

Swapping `I(NULL)` for `list()` seems to work fine, though they do have slightly different behaviors (the former ends up with the "AsIs" class). All tests pass locally, and the diff can be found [here](https://github.com/bokeh/rbokeh/compare/master...aforren1:null-warnings).

Related reading:
https://stat.ethz.ch/pipermail/r-devel/2016-December/073554.html
https://stat.ethz.ch/pipermail/r-package-devel/2016q4/001228.html
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17198

**Comment by hafen** [comment]
Thanks. I have fixed this, among other things in the master branch of `hafen/rbokeh`. After a little more testing and sanity checks, I'll merge it here and publish to CRAN. If you find any issues with it let me know.

**Comment by aforren1** [comment]
Thanks! Your master branch worked fine for me.

**Comment by region-spotteR** [comment]
On R 3.5.1. I get the warning again. I first had the CRAN-version, then removed it and get the warning again with the Github-Version (used installation with devtools) :(

**Comment by hafen** [comment]
Thanks for bring this up again. I'll try to get the right fix on CRAN this week.

**Comment by lcougnaud** [comment]
I also get the same warnings on R 3.5.1, with the package esetVis (I am the maintainer): [BUILD report](http://bioconductor.org/checkResults/devel/bioc-LATEST/esetVis/malbec1-buildsrc.html).

**Comment by hafen** [comment]
I'm pushing the updated version to CRAN today.
