### ISSUE TITLE
could not find function "ly_abline"

### ISSUE THREAD

**Issue by colinbrislawn** [bokeh/rbokeh#243]
This question should be really easy, but I'm stumped and would appreciate your help.

I have rbokeh install through bioconda, and the `ly_abline()` is missing. It's a mystery! 🕵 

```bash
$ conda list | grep rbokeh
r-rbokeh                  0.6.3                    r351_0    r

$ conda info

     active environment : r
    active env location : /miniconda3/envs/r
            shell level : 2
       user config file : /Users/cbrisl/.condarc
 populated config files : /Users/cbrisl/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch

```

```R
> library(rbokeh)
> packageVersion("rbokeh")
[1] ‘0.6.3’
> ly_abline()
Error in ly_abline() : could not find function "ly_abline"
> ?ly_abline
No documentation for ‘ly_abline’ in specified packages and libraries:
you could try ‘??ly_abline’
```

**Comment by hafen** [comment]
That's strange that 0.6.3 got installed. That version is under development and has not been released. Was rbokeh installed as a dependency of some other package, in which it might have explicitly pointed to the development branch of this version of rbokeh?

Note that we are hoping to release 0.6 some time soon, but in the mean time, please stick with the released (master branch, CRAN) version.

**Comment by colinbrislawn** [comment]
Works for me.

I look forward towards 6.0 being released!

It looks like both the [official r chanel](https://anaconda.org/r/r-rbokeh 
) and [anaconda chanel](https://anaconda.org/anaconda/r-rbokeh) are shipping 0.6.3, while [conda-forge is shipping 0.5.0](https://anaconda.org/conda-forge/r-rbokeh). Interesting!

**Comment by hafen** [comment]
Yes very interesting. That's strange since those are just sitting out on obscure branches.

**Comment by bryevdv** [comment]
Probably worth pinging someone at Anaconda about this.

**Comment by colinbrislawn** [comment]
Yep. Just thinking that 😉
I've mostly worked with bioconda and conda-forge. Do you know a good contact for the default repos?

**Comment by bryevdv** [comment]
@msarahan if not the right person himself, would probably know who is

**Comment by katietz** [comment]
Hi you all.  I am right now responsible for updating R packages in anaconda's aggregateR from CRAN.  That package r-rbokeh-feedstock was created before my time, and it is actually an import of conda-forge.  The version provided on CRAN is still 0.5.0 (as you said).  I will try to clarify, why it uses here already 0.6.3 version. Maybe @mingwandroid knows more.  But when we change, we need to change r-essentials too.
That "strange" branch you mention is actually the update-branch for CRAN … it will become soon our new master of aggregateR

**Comment by katietz** [comment]
The version was changed by me back on the 25th of April this year in context of an CRAN update … pretty strange that at that time version 0.6.3 was created.  I will take care that version gets downgrade to 0.5.0
