### ISSUE TITLE
parameter "image_url" in ly_image_url() not work for local image

### ISSUE THREAD

**Issue by zyllifeworld** [bokeh/rbokeh#247]
Hi,

I'm trying to  add a image layer to the graph panel use ly_image_url(), but it seems does not work.

here is my code:

```r
p <- figure(xlab = "x", ylab = "y", height = 450) %>%
  ly_image_url(0, 0, w = 500, h = 600, image_url = "./local/image/XXX.png",
               anchor = "center") 
p
```
I will be grateful for help.

**Comment by bryevdv** [comment]
Modern browsers will not allow loading local images into HTML canvases for security reasons. There is no way to make this work.

**Comment by zyllifeworld** [comment]
@bryevdv thanks for your timely  reply. I agree with you, I think it maybe possible just for shiny app.  Based on the discuss from this issue. https://github.com/rstudio/leaflet/issues/634. I came up a solution may work for shiny app in https://github.com/rstudio/leaflet/issues/674.


![bokeh_plot](https://user-images.githubusercontent.com/25735636/140268025-0ab9fb45-34e2-4287-988f-d1b0328b4f77.png)

I will closed this issue.
