### ISSUE TITLE
palette does not seem to pass through with `ly_image`

### ISSUE THREAD

**Issue by timelyportfolio** [bokeh/rbokeh#33]
The`palette` parameter does not seem to be working, or I'm just screwing up.  In either case, could you please confirm?  I am using these [palettes](http://bokeh.pydata.org/en/latest/docs/reference/palettes.html) and these [lines from rbokeh](https://github.com/bokeh/rbokeh/blob/6fa59d39e445c7dfe6e087a62117875956b846b3/R/themes.R#L107-L314) as reference.  I get no error like I would with `ly_hexbin`.

```
figure(height = 400,width=700) %>%
    ly_image(
      volcano
      ,palette="Blues9"
    )
```

**Comment by hafen** [comment]
Is this one closed?
