### ISSUE TITLE
text layer shows [object Object] for single row data.frame

### ISSUE THREAD

**Issue by jrowen** [bokeh/rbokeh#38]
This layer is not showing text as expected when a single row `data.frame` is used
```
DF = data.frame(x = 1, y = 1, text = "here")
figure() %>%
  ly_text(x = x, y = y, text = text, data = DF)
```
but adding another row works as expected
```
DF = data.frame(x = 1, y = 1, text = "here")
DF = rbind(DF, data.frame(x = 2, y = 2, text = "there"))
figure() %>%
  ly_text(x = x, y = y, text = text, data = DF)
```
This was an attempt to annotate a single point on a chart.

**Comment by timelyportfolio** [comment]
I ran into this also, and my fix required forcing `RJSONIO` to work correctly.  Try `text = list(text)`.

related to #30

**Comment by jrowen** [comment]
That did it, thanks.  Great package, excited to try out the shiny integration when available.
