### ISSUE TITLE
ly_lines() gives error when using color parameter

### ISSUE THREAD

**Issue by paullemmens** [bokeh/rbokeh#41]
Following the online documentation, I think that the color argument of `ly_lines()` should work in the same way as for `ly_points()`. However, I get a funky error message in the former case.

    # default example works.
    figure() %>% ly_points(Sepal.Length, Sepal.Width, data = iris, color = Species)

    # substitute ly_lines for ly_points and it throws error.
    figure() %>% ly_lines(Sepal.Length, Sepal.Width, data = iris, color = Species)
    Error in nchar(opts[[fld]]) : 'nchar()' requires a character vector

    # it appears to have to do something with Species being a factor, because if that class is removed
    # then the plot appears (but ignores coloration of the levels of Species).
    iris$Species <- as.character(levels(iris$Species))[iris$Species]
    figure() %>% ly_lines(Sepal.Length, Sepal.Width, data = iris, color = Species)

Superficially (to my inexperienced eyes), the code handling the color parameter is highly similar between `ly_points()` and `ly_lines()` but apparently, something elsewhere messes up.

**Comment by hafen** [comment]
Thanks for the report.  You're correct that it should behave in the same way.  I'll check it out, although I may be a bit slow as I'm in all-day meetings for the next few days.  If you need an immediate fix, you can pass hard-coded colors:

```
iris$col <- c("red", "blue", "green")[as.integer(iris$Species)]
figure() %>% ly_lines(Sepal.Length, Sepal.Width, data = iris, color = col)
```

Although this should kick out a legend as well.

**Comment by hafen** [comment]
Give this a shot now.

**Comment by paullemmens** [comment]
I did an update using another call to `install_github()` but now I am getting an error message that function `figure()` can't be found:

    > figure(width = 1024, height = 512) %>% 
    +   ly_lines(x = t.stamp, y = tee, fill_color = algo, data = d)
    Error in eval(expr, envir, enclos) : could not find function "figure"

Is this me being silly?

**Comment by paullemmens** [comment]
So yeah that was my bad. Apparently there's a difference between `install_github('ramnath/rbokeh')` and `install_github('bokeh/rbokeh')` ... being puzzled.

But yes, this version's color parameter works!

**Comment by hafen** [comment]
Glad to hear it works for you!
