### ISSUE TITLE
custom scales on axes

### ISSUE THREAD

**Issue by benmarwick** [bokeh/rbokeh#42]
With ggplot2 I can do `scale_y_continuous(trans=log2_trans())` to transform the scale of the y-axis to base 2 logs. How can I do this with rbokeh? All I can see is `y_axis(log = TRUE)`
thanks!

**Comment by hafen** [comment]
Good request.  I'll put this in, hopefully tomorrow.  I think usage will be like `ly_axis(log = 2)`.

**Comment by hafen** [comment]
This should work now.  Usage can still be `log = TRUE` which will give you a base 10 axis, or `log = n` where n is a numeric base.

**Comment by benmarwick** [comment]
Thanks for the quick look. I'm not sure that it's quite working right. For example, with this code

```
p2 <- figure() %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
            color = Species, glyph = Species,
            hover = list(Sepal.Length, Sepal.Width)) %>%
  y_axis(log = 2) 
p2
```

I get this plot, and the upper y axis tick shows 10^1, or 10, yet the data values above the tick are only 5.2, 5.7, etc. So the tick marks seem a bit out. 

![clipboard01](https://cloud.githubusercontent.com/assets/1262179/6423398/765881e8-be9a-11e4-988c-69a1e2f5436d.png)

**Comment by hafen** [comment]
Yikes.  If you zoom in or out a little, it is correct.  But in between is a sweet spot that is way off.  I would guess that this is a BokehJS issue.  @bryevdv, does this look like something you have encountered before?

**Comment by hafen** [comment]
See this gist to look at the model: https://gist.github.com/hafen/4529b7698943d52fc30a

**Comment by tonyfast** [comment]
@hafen If you rename the HTML file in your gist to ``index.html`` then you can view it on http://bl.ocks.org

* [Gist](http://gist.github.com/tonyfast/fb5a2a3b6f0b2704b53f/)
* [bl.ock](http://bl.ocks.org/tonyfast/raw/fb5a2a3b6f0b2704b53f/)
* [raw view](http://bl.ocks.org/tonyfast/raw/fb5a2a3b6f0b2704b53f/)

[Read more about bl.ocks.org](http://bl.ocks.org/)
