### ISSUE TITLE
What is the command to export a graph to an independant HTML web page ?

### ISSUE THREAD

**Issue by blaquans** [bokeh/rbokeh#43]
Is it possible to export an rBokeh graph to an independant HTML page ?

**Comment by hafen** [comment]
That's a good feature request.  The ability is there - I will just need to add a few helper functions to make it easy.  Should be a quick easy addition - I'll do it soon.

**Comment by hafen** [comment]
Take a look at the new function `get_bokeh_html()`:

```
p <- figure() %>% ly_points(1:10)
cat(get_bokeh_html(p))
```

Is this along the lines of what you were thinking?  You'll have to place the `<head>`, `<div>` and `<script>` segments in their appropriate places.  This works but if there are suggestions to make it more convenient, let me know.

**Comment by blaquans** [comment]
Thanks for this nice feature.

**Comment by apoku** [comment]
Do you have an example of how to embed plots inline within an iPython Jupyter/Notebook? I've tried embedding HTML with the get_bokeh_html(fig) approach with no luck (results in an inline blank image notated with red font Javascript error. If I open the saved off html file I get the same errors )

JS errors in the JS console: 
Uncaught Error: field value for property 'x' is not a string (CDN calling Bokeh 0.9.1, 0.9.2)
Uncaught TypeError: t.default_view is not a function (CDN calling Bokeh 0.8.1)

These are the relevant cells in my iPython Jupyter notebook
```
--- cell #1 ---
%%R
library(rbokeh)
p <- figure() %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width))

h <- p
cat(get_bokeh_html(p), file="tryit.html")

--- cell #2 ---
%R -o h

--- cell #3 (bokeh 0.8.1 and 0.9.2 result in different JS errors) ---
blurb = h[0]
blurb = blurb.replace('0.8.1', '0.9.2')
blurb = blurb.replace('\n','')


--- cell #4 ---
from IPython.core.display import HTML

HTML(blurb)
