### ISSUE TITLE
Should xlim reverse x axis scale?

### ISSUE THREAD

**Issue by markcassar** [bokeh/rbokeh#48]
Great project! Thanks for developing. 

I was expecting xlim=c(10,0) to reverse the x axis scale but the order seems to be ignored, though it will adjust the limits appropriately.

**Comment by hafen** [comment]
Thanks - good point.  I hadn't thought of that case.  This should be doable.  I'l work on it.

**Comment by bryevdv** [comment]
I do believe just switching the start/end should work on the BokehJS side:

    http://jsfiddle.net/d9bva8Lp/1/

I think there may be some edge cases involving images that are broken but everything else should be fine.

**Comment by markcassar** [comment]
Cool, thanks
