### ISSUE TITLE
Question about ly_rect

### ISSUE THREAD

**Issue by sdc3** [bokeh/rbokeh#58]
Hello,

The following code:

```r
library(rbokeh)
my_data = data.frame(xleft = 1, xright = 5, ybottom=1, ytop=3)
figure() %>% ly_rect(xleft=xleft, ybottom=ybottom, xright=xright, ytop=ytop, data = my_data)
```

Gives an error:
```r
Error in v_eval(substitute(yright), data) : 
  argument 'yright' is not present in the 'data' argument
```

Is the code wrong?
Shouldn't `yright` be replaced by `xright` in line 121 of layer_shapes.R?

Thank you for this awesome package!

```r
## R version 3.1.2 (2014-10-31)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## rbokeh_0.2.2
```

**Comment by hafen** [comment]
Wow thanks for catching that!  Not sure how that slipped through.  I'll fix when I'm at a computer this evening.

**Comment by hafen** [comment]
This should be fixed.  Thanks for the detailed report and finding the problem.
