### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by asmeurer** [bokeh/rbokeh#61]
Can you push tags for all your releases to GitHub. It will make it much easier to build conda packages.

**Comment by hafen** [comment]
Sure.  I'm not familiar with how conda works with GitHub.  Do you need just tags or do you need tagged releases with package tarballs?

**Comment by asmeurer** [comment]
I can build packages just from the tag. Package tarballs could potentially be useful for other people, although if you don't change anything from git to the tarball GitHub generates these from tags on the releases page automatically.

**Comment by hafen** [comment]
Sorry for the delay.  I've tagged the current version and will make it a practice for all version bumps in the future.
