### ISSUE TITLE
Hover on categorical data

### ISSUE THREAD

**Issue by carbonmetrics** [bokeh/rbokeh#62]
I am trying to get hovering on a plot with categorical data on the y-axis. It does not seem to work. Here is the code [p1 does not give hovering info, p2 does]:

data(mtcars)
mtcars$models = factor(row.names(mtcars))

p1 = figure() %>%
  ly_points(mpg, models, data = mtcars, 
            hover = list(mpg, models))

p2 = figure() %>%
  ly_points(disp, mpg, data = mtcars,
            hover = c(disp, mpg))

grid_plot(list(p1,p2),link_data = T)

**Comment by hafen** [comment]
This is an open issue with bokeh having to do with circles and categorical axes:

https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/pFmgm_wu4Ds/yrYx958GbcoJ

https://github.com/bokeh/bokeh/issues/624

It seems to be limited to circles, so you could try ly_crect or something in the mean time.  I'm hoping this one will be resolved soon.

**Comment by carbonmetrics** [comment]
Maybe related to this: I can't seem to make ablines in a cat/num figure. [I often make 2 dashed vertical lines that indicate "control limits"].

**Comment by hafen** [comment]
`ly_abline` is only intended for num/num figures.  You should be able to get what you are after by using `ly_segment`.

**Comment by carbonmetrics** [comment]
I've thought of that but then couldn't think of a way to define y0 and y1 on the cat axis.

**Comment by hafen** [comment]
It would just have to be the lowest and highest categorical values.  Here's an example:

```
library(rbokeh)
figure() %>%
  ly_points(1:26, letters) %>%
  ly_segments(10, "a", 10, "z")
```

Here you don't quite extend beyond the "a" and "z", so you can do something like this (not well-documented)

```
figure() %>%
  ly_points(1:26, letters) %>%
  ly_segments(10, "a:0", 10, "z:1")
```

**Comment by carbonmetrics** [comment]
Yes, this works! Thanks...

**Comment by hafen** [comment]
@carbonmetrics, I believe this is fixed with the latest version of Bokeh.  Still doing some testing but should pretty stable:

```
devtools::install_github("hafen/rbokeh@bokeh-v0.9")
```

**Comment by timelyportfolio** [comment]
Nice, this works for me now.  @carbonmetrics, can you confirm?

**Comment by carbonmetrics** [comment]
This works...thanks! 

SessionInfo :

    R version 3.2.0 (2015-04-16)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.2 LTS
    rbokeh 0.2.3

**Comment by hafen** [comment]
The original problem stated here dealing with hover using circles in categorical axes should be fixed now in the dev branch.  You can test with `install_github("bokeh/rbokeh@dev")`

**Comment by hafen** [comment]
BTW this fix basically came from updating to the latest bokeh version.

**Comment by hafen** [comment]
@carbonmetrics sorry I've been going through old issues and just noticed you had asked a question I didn't answer.  To get your cat axis in alphabetical order, you specify the order you want the axis to be in through the xlim or ylim argument to figure().
