### ISSUE TITLE
Creating standalone plots

### ISSUE THREAD

**Issue by carbonmetrics** [bokeh/rbokeh#64]
I would like to create standalone html pages. Generating html like this works:

````
output:
  html_document:
    self_contained: no
---

```{r}
library(rbokeh)
 figure() %>% ly_points(cars$speed, cars$dist)
```

but as soon as I select "Create a standalone HTML document" I get a pandoc 67 error:

```
pandoc: Could not fetch /home/henk/R/x86_64-pc-linux-gnu-library/3.2/rbokeh/htmlwidgets/lib/bokehjs/images/ui-bg_flat_75_ffffff_40x100.png
/home/henk/R/x86_64-pc-linux-gnu-library/3.2/rbokeh/htmlwidgets/lib/bokehjs/images/ui-bg_flat_75_ffffff_40x100.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted
```
So the question is: how can I generate a standalone HTML file?

**Comment by Rnewbie** [comment]
May be you can use shinny to make HTML. This is the code template from code issue #25 

```
library(shiny)
library(rbokeh)

ui = shinyUI(fluidPage(
  rbokehOutput('a_bokeh_plot' )
))

server = function(input, output){
  output$a_bokeh_plot <- renderRbokeh({
    figure() %>% ly_points(cars$speed, cars$dist)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by carbonmetrics** [comment]
Thanks! If I run this I see a page with R code on it and no plot [after > Run Document]. I never dived into Shiny, so if this is a purely Shiny related let me know...

**Comment by Rnewbie** [comment]
Hey , you just install shiny development version with devtools. It will work fine. I think the shiny library you are using it is fron CRAN. Please find a way to install shiny from dev. Its kind of like...please check for correctneess...

devtools::install_github('rstudio/shiny')

I am using my phone to type. Sry


--- Original Message ---

**Comment by carbonmetrics** [comment]
Thanks! Downloaded from github, but same results. I thought you would start the app by just clicking "Run Document" or is there a different method?

**Comment by Rnewbie** [comment]
Yes you can do if you got ui.R and shinny.R and call function runApp()  this is wired cause in the morning i got same problem as you and it was solved when i install shinny from github. 

When you run this

'''
figure() %>% ly_points(cars$speed, cars$dist) 
'''
It gives you a interactive graph right?

**Comment by carbonmetrics** [comment]
it works! thanks...saved me a few grey hairs ;-)

**Comment by Rnewbie** [comment]
Hey cool. We are using a cutting edge technology man.

**Comment by timelyportfolio** [comment]
I believe this is an issue that needs to be resolved where Pandoc finds the pattern *.png in the CSS comment and believes it needs to `base64` encode the `png` even though it does not.  I'll test and hopefully push a fix.

**Comment by Rnewbie** [comment]
Hey, timelyporfolio thanks for the insights. I also got the same issues when   i try to make a html page using rboken from knit button in Rstudio. But with shiny, html with rbokeh is amazing.

**Comment by bryevdv** [comment]
> But with shiny, html with rbokeh is amazing.

Hey I jut wanted to chime in. Love seeing comments like this. :) Lots of folks at my last conference  tutorial asking "but who's using Bokeh?" So I'd really like to get a "testimonials" or "user stories" page up soon. Of course this depends on people doing public work with Bokeh, and being willing to be referenced/cited. Ideally a gallery, but even links/mentions would be good to start collecting. If this describes you, if you are doing something public-facing with Bokeh and would not mind being showcased or mentioned, please let us know!

**Comment by timelyportfolio** [comment]
@hafen, this is #40 plus a little more. I guess we need to figure out the best way to automate the base64 piece of the `svg` in css unless @bryevdv can do it in `bokeh` on the source side.

Copying all the images/icons will be permanent so we won't have to do this each time.

**Comment by bryevdv** [comment]
@hafen @timelyportfolio Possibly, what is it exactly that would need to be handled differently?

**Comment by timelyportfolio** [comment]
@bryevdv I hesitate to ask since I'm not competent enough to know of any other downstream implications.  I believe there to be none.

well, it still does not show up cleanly, but the effect is on this line

we go from

```
.bk-logo.grey{filter:url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");filter:gray;-webkit-filter:grayscale(100%)}
```

to

```
.bk-logo.grey{filter:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPjxmaWx0ZXIgaWQ9J2dyYXlzY2FsZSc+PGZlQ29sb3JNYXRyaXggdHlwZT0nbWF0cml4JyB2YWx1ZXM9JzAuMzMzMyAwLjMzMzMgMC4zMzMzIDAgMCAwLjMzMzMgMC4zMzMzIDAuMzMzMyAwIDAgMC4zMzMzIDAuMzMzMyAwLjMzMzMgMCAwIDAgMCAwIDEgMCcvPjwvZmlsdGVyPjwvc3ZnPg==");filter:gray;-webkit-filter:grayscale(100%)}

```
There are a couple ways to do it, but in R, we can
```
base64enc::base64encode(charToRaw("<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>"))
```
and then change utf8 to base64 and replace the svg tag with the base64 value.

**Comment by Rnewbie** [comment]
Hi, bryevdv. You rock. This is so cool. I am happy to the maximum now to get a comment from core bokeh maker. Its like a dream.
