### ISSUE TITLE
rbokehOutput, size of output

### ISSUE THREAD

**Issue by carbonmetrics** [bokeh/rbokeh#66]
via ??rbokehOutput, I get rbokeh::rbokehOutput with an example, see code below.

The example does not work, see comments and modification. 

The question is: how do I increase height and width of the figure? The current size is too small [have to scroll]. The help says rbokehOutput(outputId, width = '100%', height = '400px'), but this does not affect the output in my case.

```
output:
  html_document:
    self_contained: no
runtime: shiny
---
{r}
library("shiny")
library("rbokeh")
library("htmlwidgets")

ui <- fluidPage(
  rbokehOutput("rbokeh", width = 500, height = 800)
)

server <- function(input, output, session) {
  output$rbokeh <- renderRbokeh({
    # Use invalidateLater() and jitter() to add some motion
    # invalidateLater(1000, session)  # continuous stream of xlim not specified explicitly... calculating...;  ylim not specified explicitly... calculating...
    p <- figure() %>%
      ly_points(jitter(cars$speed), jitter(cars$dist))
    # rbokeh:::plot.BokehFigure(p)  # does not work
    p  # works
  })
}

shinyApp(ui, server)
```

```

**Comment by Rnewbie** [comment]
Hey carbonmetrics, try with width = 100% and height = 100%. rbokeh graphs are interactive so people can adjust the size anyway they want. Good luck playing with robkeh. I am going to date with R now. hope it helps. 

```
library("shiny")
library("rbokeh")
library("htmlwidgets")

ui <- fluidPage(
  rbokehOutput("rbokeh", width = "100%", height = "100%")
)

server <- function(input, output, session) {
  output$rbokeh <- renderRbokeh({
    # Use invalidateLater() and jitter() to add some motion
    # invalidateLater(1000, session)  # continuous stream of xlim not specified explicitly... calculating...;  ylim not specified explicitly... calculating...
    p <- figure() %>%
      ly_points(jitter(cars$speed), jitter(cars$dist))
    # rbokeh:::plot.BokehFigure(p)  # does not work
    p  # works
  })
}

shinyApp(ui, server)
```

**Comment by carbonmetrics** [comment]
Whatever percentage [or px] I put there, the size of the output does not change. 
[I don't have this problem when I render a html file].

**Comment by hafen** [comment]
I'll take a look at this tomorrow.

**Comment by hafen** [comment]
@carbonmetrics I'm looking at this now and your example is not working.  What version of the package and htmlwidgets do you have installed?

**Comment by carbonmetrics** [comment]
@hafen - here is some session info. Tested again by copying/pasting from example above [added output header],  everything works normally. 

R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8        LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8           LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8      LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

knitr_1.9
shiny_0.11.1.9004
htmlwidgets_0.3.3
rbokeh_0.2.2

**Comment by hafen** [comment]
I think this is fixed.  Could you install from here:

```
devtools::install_github("hafen/rbokeh")
```

And let me know if it fixes your issue?

Note that this fix will not work with `grid_plot()` since it is difficult to figure out how to resize all the individual panels - that needs some more work.

One thing you can always do is specify the same dimensions in your call to `figure()` that you do to `renderBokeh()`.  You won't have to do that with this fix anymore, but that was an option prior.

Let me know if it works and I'll merge to bokeh/rbokeh.

**Comment by carbonmetrics** [comment]
It has helped to change the dimensions of the figure within the window created by shiny. 
However the window created by shiny is too small - that is something that needs to be enlarged too when I enlarge the figure. The result is now a larger figure that is mostly invisible because of the small shiny window.

**Comment by hafen** [comment]
I'm not sure I understand what you mean.  Could you provide an example?

**Comment by carbonmetrics** [comment]
The best way of explaining is the screenshot. I have increased the size of the figure  in the rbokehOutput part, but only part of the plot is visible - it is masked by the shiny window.

![selection_014](https://cloud.githubusercontent.com/assets/4662049/7489295/7c47943e-f3d5-11e4-89fc-b4f6db194cf1.png)

**Comment by hafen** [comment]
Whatever you specify as the width and height will be honored.  Since 900px is bigger than the window size it will overflow and you have to scroll.  You can specify width='100%' if you want to fill the window width.  I think this is how widget outputs are supposed to behave.  If you have examples of other htmlwidgets that behave differently, please let me know and I'll see if I should do something differently.

**Comment by carbonmetrics** [comment]
I have set both width and height to 80%. The width is right, the height didn't change. 

I see your point - this is more shiny than rbokeh. The problem arises when you want to use grid_plot and you want to share that with somebody else via shiny. In that case there is just not enough space [which would be a shame, grid_plot is fantastic]. Via html there is no problem - I just specify large sizes in the knitr chunk.

**Comment by hafen** [comment]
The height issue probably has to do with the web browser - percent heights only work if the parent element has a fixed height.

For grid_plot, you can probably do some things like reduce the font size, etc. to make it work.
