### ISSUE TITLE
named lists do not work with grid_plot

### ISSUE THREAD

**Issue by timelyportfolio** [bokeh/rbokeh#7]
Not necessarily a bug, but probably should be documented that named lists don't work in `grid_plot`.  I guess could easily `unname` any list passed as `x` in `grid_plot`.

**Comment by hafen** [comment]
Good catch.  Yes, let's add an `unname`.  I can do that while I address #6.

**Comment by hafen** [comment]
@timelyportfolio, would you mind taking a look at this one to make sure the fix addresses what you were seeing?  I simply added `unname()`.

**Comment by timelyportfolio** [comment]
sure, I'll check it out now.  I got this when I used `sapply` instead of `lapply`.

**Comment by hafen** [comment]
Actually hold on for a few minutes.  It looks like Travis misled me into thinking things were good when I merged.  Need to check something quickly.

**Comment by timelyportfolio** [comment]
Also, good now.  Will close.
