### ISSUE TITLE
Unable to pass data.frame as hover parameter when using lapply

### ISSUE THREAD

**Issue by jrowen** [bokeh/rbokeh#72]
Hover does not work with the example below.  I think the problem is related to the [`substitute`](https://github.com/bokeh/rbokeh/blob/master/R/layer_points.R#L50) call being used to pass the `hover` parameter to `rbokeh:::get_hover`.  In the example below, the `tmp` data.frame is not being found by `substitute`.
```
library(rbokeh)
DF = data.frame(x=1:10, y=1:10, z=11:20)
grid_plot(lapply(1:4, function(i) {
  tmp = DF
  figure() %>%
    ly_points(x = x, y = y, data = tmp, hover = tmp[, c("x", "z")])
}))
```
The change below looks like it may fix the issue.  I'll admit I'm not very familiar with `substitute` and `eval`, so there may be a better solution.
```
if (is.data.frame(hover))
    hover <- get_hover(hover, data)
else
    hover <- get_hover(substitute(hover), data)
```

**Comment by hafen** [comment]
Lazy evaluation can be tricky with cases like this.  Try the inside part of  your loop on its own and it works fine.

A good practice in general when using hover is to make sure the hover columns are in the data frame passed as the `data` argument (and if they aren't, add them).

For example, the following modification to your example:

```
library(rbokeh)
DF = data.frame(x=1:10, y=1:10, z=11:20)
grid_plot(lapply(1:4, function(i) {
  tmp = DF
  figure() %>%
    ly_points(x = x, y = y, data = tmp, hover = c(x, z))
}))
```

The problem with your fix above is that `if (is.data.frame(hover))` will try to evaluate `hover`, which will result in an error if it is not an actual object but just an expression.

**Comment by jrowen** [comment]
I see what you mean--this is a tough one.  If #73 is merged, I could see a use case like the example below, which is how I stumbled upon this issue.
```
DT = data.table(x=rnorm(10), y=rnorm(10), z=rep(1:2, 5))
grid_plot(lapply(1:2, function(i) {
  DT_ = DT[z == i]
  figure() %>%
    ly_points(x = x, y = y, data = DT_, 
              hover = DT_[, list(x = round(x, 2), y = round(y, 2))])
}))
```
How about this approach?
```
  if (tryCatch(is.data.frame(hover), error = function(e) return(FALSE)))
    hover <- get_hover(hover, data)
  else
    hover <- get_hover(substitute(hover), data)
```
