### ISSUE TITLE
plot vectors

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#74]
rbokeh requires all vectors to be converted to dataframes which increases the memory required. Also even if i want to plot just one point on a curve I have to put those points in a dataframe as well.

Please allow plotting of vectors and single points without requiring them to be in a dataframe

**Comment by hafen** [comment]
Could you be more specific or provide an example?  Vectors and scalars work just fine, e.g.:

```
figure() %>% ly_points(1:10, 1:10)
```

Also, if your data is so large that memory is a concern, you might want to rethink what you are plotting.  Every data point is sent to the browser and individually rendered, so you don't want to be sending massive amounts of data to an rbokeh figure.

**Comment by MySchizoBuddy** [comment]
Thanks my mistake
