### ISSUE TITLE
R - rbokeh and htmlwidgets Compatibility

### ISSUE THREAD

**Issue by benfasoli** [bokeh/rbokeh#76]
Receiving the following error when attempting to use the current version of rbokeh.h

Error in htmlwidgets::createWidget(name = "rbokeh", x = list(spec = spec,  : 
  unused argument (preRenderHook = rbokeh_prerender)

**Comment by hafen** [comment]
See here: https://github.com/bokeh/rbokeh/issues/70

**Comment by hafen** [comment]
This should now work with htmlwidgets installed from CRAN as well as it has been updated.  I will close as this has been a common issue that should now be fixed.  If you still experience issues, please reopen.  Thanks.
