### ISSUE TITLE
Multiple hover tool

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#78]
Using the bokeh-0.9 branch I see multiple hover tool checkboxes on windows 8.1 Rstudio version 0.99.441
![rplot](https://cloud.githubusercontent.com/assets/51676/7824801/ef92c176-03ba-11e5-84f1-df268dd3113a.png)

**Comment by hafen** [comment]
This is expected behavior (same behavior under other versions as well).  There are three different glyphs being drawn.  Each has its own hover tool.
