### ISSUE TITLE
grid_plot not displaying properly with shiny

### ISSUE THREAD

**Issue by jrowen** [bokeh/rbokeh#79]
In the example below, the individual grid plots become "compressed" (y-axis collapses onto itself at at the x-axis; point not visible) after the second change of select the dropdown.
```
library(shiny)
library(rbokeh)

df = rbind(
  data.frame(bucket = "First", group = rep(c("a", "b"), 5), x = rnorm(10), y = rnorm(10)),
  data.frame(bucket = "Second", group = rep(c("a", "b"), 5), x = rnorm(10), y = rnorm(10))
)

ui = shinyUI(fixedPage(
  fixedRow(
    selectInput("bucket", "Bucket", c("First", "Second"))
  ),
  fixedRow(
    rbokehOutput("rbka")
  )
))

server = function(input, output) {
  output$rbka <- renderRbokeh({
    tmp = df[df$bucket == input$bucket, ]
    grid_plot(lapply(unique(df$group), function(x) {
      figure(xlab = "x", ylab = "y") %>%
        ly_points(x, y, data = tmp[tmp$group == x, ])
    }))
  })
}

shinyApp(ui = ui, server = server)
```
I'm using v0.2.3.1 and don't see any error messages in the JS console.  Specifying `ylim` and `xlim` doesn't help.

**Comment by hafen** [comment]
Interesting.  I've actually seen something like this before when embedding rbokeh plots in trelliscope.  And it only happened with grid plots.  This will be tricky to track down and my guess would be that it is a bokeh issue or an issue with the code in rbokeh.js to embed the plots.  I'll look into it.

**Comment by hafen** [comment]
Figured this one out - `tool_events` and `grid_plot` were not getting unique ids because they weren't picking up the `Sys.time()` that helps make the id unique.  I'm guessing something with tool events and a tool dealing with ranges was remaining on the page when a new grid plot was added.

**Comment by jrowen** [comment]
Confirmed it's fixed, thanks.  I wouldn't have thought to check unique ids.
