### ISSUE TITLE
bar chart

### ISSUE THREAD

**Issue by timelyportfolio** [bokeh/rbokeh#8]
I did not see how to make a bar chart, so I assume it is not possible.  If not, I think a bar chart would be nice.  I know bokeh supports bars http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#bar.

**Comment by hafen** [comment]
Yes this is one I didn't have time to add.  We need a good robust `ly_bars()`.  @saptarshiguha, is this something you would like to work on?  Basically we need a function that will translate the input appropriately into rect glyphs to draw the bar chart.

**Comment by saptarshiguha** [comment]
I'll give it a shot. Will be slow given other commitments.

**Comment by timelyportfolio** [comment]
This is the Python equivalent https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/bar_builder.py, correct?

**Comment by hafen** [comment]
@timelyportfolio - yes, that's correct.  @saptarshiguha, if you're pretty busy right now, that's ok - there will always be plenty of interesting things to work on :).  @timelyportfolio, what kind of bandwidth do you have for contributing?  There will be a ramp-up cost for sure (I should start a wiki page that describes how some things work), but hopefully once the design is clear, things should be pretty smooth.

**Comment by timelyportfolio** [comment]
I have a little bit of time and should be able to work on it.  Do you want this in before release?  What is your timeline for release?

**Comment by hafen** [comment]
I think the idea is to release when 0.8 is officially announced, which is sometime next week, right, @bryevdv ?  If you think it's doable in that short of a time frame, then it would be great.  But if not, it's fine - I think it will be okay to release something that doesn't have everything in it that we'd like right off the bat.  I'm creating a "release" milestone now.  For sure we want to work with 0.8 and ideally make use of the awesome GMapPlot type and click to open URL.  Those should be quick.

**Comment by bryevdv** [comment]
Yes Bokeh 0.8 will be released on the morning (CST) 17th. In general there is no need to sync up releases, and for this one in particular, whatever is ready will be fantastic!

**Comment by hafen** [comment]
Sounds good.  Yeah I think after the initial release, we'll just release as things move along.  But I want to make sure we're making use of 0.8 for the initial.

So @timelyportfolio , since the 17th is soon and we should be making sure everything works with 0.8, we can push this one out to after initial release.

**Comment by timelyportfolio** [comment]
@hafen, here is what I [have so far](https://github.com/timelyportfolio/rBokeh/tree/feature/stats_bar) (ugly and embarrassing), but it's something.  No stacks, and I don't think anyway to label the axis properly.

```
#devtools::install_github("timelyportfolio/rbokeh@feature/stats_bar")
library(rbokeh)
library(dplyr)
library(pipeR)

figure() %>>%
  ly_bar(
    x = cyl, y = mpg,
    data =  mtcars %>>%
      group_by( cyl ) %>>%
      summarise( mpg = mean(mpg) ) %>>%
      (
        rbind(
          data.frame( group = "A", . )
          ,data.frame( group = "B", . )
        )
      )
  )



figure() %>>%
  ly_bar(
    x = cyl, y = mpg, group = group,
    data =  mtcars %>>%
      group_by( cyl ) %>>%
      summarise( mpg = mean(mpg) ) %>>%
      (
        rbind(
          data.frame( group = "A", . )
          ,data.frame( group = "B", . )
        )
      )
  )
```

**Comment by hafen** [comment]
Thanks!  Looks like a good start.  I'll take a closer look Monday.

**Comment by timelyportfolio** [comment]
Will definitely need to push this out past initial release.  Still not sure the axis labelling will be possible, but need to work through the most recent batch of pulls to see how to add a custom axis and hide the default axis.

**Comment by hafen** [comment]
Yes sorry I was going to give this a deeper look yesterday and got caught up in other things.  Sorry!  I'll take a look and see if I can save you some effort in looking through the code.

**Comment by happyshows** [comment]
@hafen is there any updates on this thread? thanks..

**Comment by hafen** [comment]
@happyshows, this is on my radar.  I'm in the middle of a busy period but this is definitely in the batch of features to add in the near term.

**Comment by hafen** [comment]
Somehow this issue fell through the cracks.  This has been implemented for some time.
