### ISSUE TITLE
Slow on large time series dataset

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#87]
I have a timeseries datatset of 8760 hours of the year in date.time format as characters.  rbokeh chocks Rstudio in displaying the graph. panning zooming is not usable.  In firefox it triggers the non-responsive script error. 

Im using date.time as characters because I don't want rbokeh to sort them, rbokeh should just display them as they appear in the dataset.

Even if they are characters rbokeh doesn't have to display all of them it can choose to skip some x values say like skip next 100 x values from displaying. When you zoom in it can then display the intermediate x values.

**Comment by hafen** [comment]
That's interesting that a data set this small is causing issues.  A branch I was working on a while back to migrate to bokeh 0.9 does include a parameter `lod_threshold` that allows you to specify the level of detail such that downsampling will occur when there are too many data points.  This will be incorporated soon.  The past month has been very hectic and I've been kept from addressing several of these issues, but I should be able to tackle this and other things very soon.  Stay tuned.

**Comment by MySchizoBuddy** [comment]
btw is there a way that rbokeh will display the x-axis date-time series without sorting them and display as they appear in the dataset. TMY3 weather/solar radiation dataset has one year data where each month data is taken from different years. 
for eg it will have rows with date-time from Jan of 1976, Feb of 2003, March of 1998... December of 2010. That together gives a year long dataset.
I don't want rbokeh to move the Feb of 2003 after March of 1998. That will mess up the graph. I also don't want it to display a large blank between Jan of 1976 and Feb of 2003.

My current solution is to change the year information of all the months to 2015. But then i'm unable to hide 2015 label appearing on the graph.

**Comment by hafen** [comment]
Without sorting, it would no longer be a date-time axis, correct?  You could just recode the variable as a character string.

**Comment by hafen** [comment]
@MySchizoBuddy, you can take a look at `install_github("bokeh/rbokeh@dev")` and look at the arguments to `figure()` such as `lod_factor`, `lod_interval`, `lod_threshold`, `lod_timeout`.
