### ISSUE TITLE
Support full control over` legend

### ISSUE THREAD

**Issue by hafen** [bokeh/rbokeh#9]
Currently just the default legend settings are used and the user has no control.  We want to provide full access to the legend model:

http://bokeh.pydata.org/en/latest/docs/reference/models.html#legend

To provide full options, this would be through a new pipable function `legend(fig, ...)` where `...` are the legend options.  But maybe also expose the most important argument `orientation` as an argument `legend_orientation` to `figure()`.

**Comment by polyphant1** [comment]
+1
