### ISSUE TITLE
Allow changing timeseries data label format 

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#95]
In the example provided

    p <- figure(width = 800, height = 400) %>%
         ly_lines(date, Freq, data = flightfreq, alpha = 0.3) %>%
         ly_points(date, Freq, data = flightfreq,
                hover = list(date, Freq, dow), size = 5

The format of the x-axis timedate isn't changeable. At-least I didn't find anything in the ly_lines() or figure() function.

**Comment by hafen** [comment]
For finer control over axis labels, use `x_axis()` or `y_axis()`.  Control over axis formats was added by @jrowen - see the documentation for the axis functions for details.  We need to document this on the main page.  Here's an example:

```
  p <- figure() %>%
    ly_lines(seq(as.Date("2012-01-01"),as.Date("2012-12-31"), by="days"), rnorm(366)) %>%
    x_axis(label = "Date", formats = list(months="%b-%Y", days="%d"))
```

**Comment by jrowen** [comment]
I should probably take a look at the main page.  Which repo would be best
to work with?

**Comment by hafen** [comment]
@jrowen that would be great if you are up for it.

The need is in this section: http://hafen.github.io/rbokeh/#axes

The docs are served here and are built with `build.R`.

https://github.com/hafen/hafen.github.io

**Comment by jrowen** [comment]
I'm having trouble building `index.Rmd`, and I think it is because of
```
load("_ignore/doubles.rda")
```
Should this chunk be removed/commented out?  If not, an you check in this data file?

**Comment by hafen** [comment]
Oh yeah - I just added it, but put it in data/doubles.rda, so you can change the path.  Thanks.

**Comment by hafen** [comment]
I've been meaning to do something about that.  Yes, we could do `@section` for each and then remove "Additional Parameters" as it would be an empty section.  Since we say things like "see additional parameters", we would need to change, for example, `\subsection{Basic Tick Format}` to `\subsection{Additional Parameters: Basic Tick Format}`.

**Comment by hafen** [comment]
Do you want to branch off of rbokeh master and make this change?  Or I'm happy to do it.

**Comment by jrowen** [comment]
Since I'm in the midst of a PR for the website doc, it might make sense for me to also take a look at the rbokeh master (assuming this is a quick update).  I can switch gears and pull together a PR for an rbokeh doc change, and then roll those updates into my website PR.

**Comment by hafen** [comment]
Sounds great.  Should be a quick thing.

**Comment by jrowen** [comment]
I'm running into another error
```R
Error in pkg_sd_path(pkg, site_path = site_path) : 
  Folder inst/staticdocs doesn't exist. Specify site_path or create a package folder inst/staticdocs.
```
Is there a folder missing from the core rbokeh project?

**Comment by hafen** [comment]
Oh this is a strange one from the staticdocs package.  Just create an empty folder called 'staticdocs' in inst.  I didn't check it in because it's not necessary for the package.  But I suppose it should be checked in so that it's easier for others to build the docs.

**Comment by jrowen** [comment]
I'll just add
```
dir.create(file.path(code_path, "inst/staticdocs"))
```

**Comment by hafen** [comment]
Sounds good.
