### ISSUE TITLE
Shiny example broken in the 0.9 branch

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#97]
The shiny example in the docs in the latest dev build "hafen/rbokeh@bokeh-v0.9" is broken.
Error

    Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
     object 'plot.BokehFigure' not found

Sorry this belongs in the hafen/rebokeh repository

**Comment by hafen** [comment]
Please ignore this branch.  dev has bokeh 0.9 in it now.

**Comment by ziyadsaeed** [comment]
the dev branch also has the same error.

**Comment by hafen** [comment]
Sorry about that - should be fixed now.  And the code is simpler too.
