### ISSUE TITLE
rbokeh dev errors out

### ISSUE THREAD

**Issue by MySchizoBuddy** [bokeh/rbokeh#98]
Using devtools::install_github("bokeh/rbokeh@dev")

the dev branch doesn't install

    Error in namespaceExport(ns, exports) : 
    undefined exports: phantom_install, save_figure
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing 'C:/Program Files/RRO/R-3.2.0/library/rbokeh'
    Error: Command failed (1)

**Comment by hafen** [comment]
Thanks - this is fixed.  I must not have CI turned on for this.  I'll look into it.
